# Generated by Django 3.0.6 on 2020-05-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_site_tld', models.CharField(max_length=150)),
                ('recipe_title', models.CharField(max_length=50)),
                ('recipe_parsed', models.BooleanField()),
            ],
        ),
    ]
