# Generated by Django 3.0.6 on 2020-05-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequests',
            name='recipe_title',
            field=models.CharField(max_length=80),
        ),
    ]
